# Generated by Django 3.0.2 on 2020-01-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chances_of_cloning', models.CharField(blank=True, choices=[('0', '0(never clone)'), ('1', '1'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10(always clone)')], default='5', max_length=2)),
            ],
        ),
    ]
