# Generated by Django 3.0.2 on 2020-01-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='should_show_red_banner_for_injected_posts',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
