# Generated by Django 2.2.1 on 2019-05-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakeLinkModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakelinkmodel',
            name='fake_link_topic',
            field=models.CharField(blank=True, default='Entertainment', max_length=1000),
        ),
    ]
