# Generated by Django 2.2.1 on 2019-05-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakeLinkModel', '0002_fakelinkmodel_fake_link_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='FakeLinkModel',
            name='short_link',
            field=models.CharField( blank=True, default='', max_length=1000)
        ),
    ]