# Generated by Django 3.0.3 on 2020-04-17 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_user_uuid'),
        ('link', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkModel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='link.LinkModel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='BriefSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfLinksSeen', models.IntegerField(default=0, null=True)),
                ('numberOfLinksClicked', models.IntegerField(default=0, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User')),
            ],
        ),
    ]
