# Generated by Django 2.2 on 2019-05-12 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_link', models.CharField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='LinkPreviewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.CharField(blank=True, default='', max_length=100)),
                ('url', models.CharField(blank=True, default='', max_length=100)),
                ('parentLink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='linkPreview.ParentLink')),
            ],
        ),
    ]
