# Generated by Django 2.2 on 2019-05-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkPreview', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkpreviewmodel',
            old_name='parentLink',
            new_name='parent_link',
        ),
    ]
