# Generated by Django 2.2 on 2019-05-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkPreview', '0002_auto_20190512_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkpreviewmodel',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='linkpreviewmodel',
            name='image',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='linkpreviewmodel',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='linkpreviewmodel',
            name='url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
