# Generated by Django 3.0.3 on 2020-05-04 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_user_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='genuine', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LinkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_text_original', models.CharField(blank=True, max_length=1000)),
                ('link_text_fake', models.CharField(blank=True, max_length=1000)),
                ('link_target_original', models.CharField(blank=True, max_length=1000)),
                ('link_target_fake', models.CharField(blank=True, max_length=1000)),
                ('link_image_src_original', models.CharField(blank=True, max_length=1000)),
                ('authored_text_original', models.CharField(blank=True, max_length=1000)),
                ('authored_text_fake', models.CharField(blank=True, max_length=1000)),
                ('author_name', models.CharField(blank=True, max_length=1000)),
                ('is_seen', models.BooleanField(default=False)),
                ('is_clicked', models.BooleanField(default=False)),
                ('is_clicked_event_from_ground_data', models.BooleanField(default=False)),
                ('is_clicked_event_from_ground_data_time', models.TimeField(blank=True)),
                ('time_to_view', models.TimeField(blank=True)),
                ('preview_title', models.CharField(blank=True, default='', max_length=1000)),
                ('preview_description', models.CharField(blank=True, default='', max_length=2000)),
                ('preview_image', models.CharField(blank=True, default='https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Simple_Rectangle_-_Semi-Transparent.svg/1594px-Simple_Rectangle_-_Semi-Transparent.svg.png', max_length=1000)),
                ('preview_url', models.CharField(blank=True, default='', max_length=1000)),
                ('link_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='link.LinkType')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User')),
            ],
        ),
    ]
