# Generated by Django 2.2 on 2019-05-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_linkmodel_link_image_src_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='preview_image',
            field=models.CharField(blank=True, default='https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Simple_Rectangle_-_Semi-Transparent.svg/1594px-Simple_Rectangle_-_Semi-Transparent.svg.png', max_length=1000),
        ),
    ]
