# Generated by Django 3.0.3 on 2020-05-05 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_auto_20190513_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkmodel',
            name='is_clicked_event_from_ground_data',
        ),
        migrations.RemoveField(
            model_name='linkmodel',
            name='is_clicked_event_from_ground_data_time',
        ),
    ]
