# Generated by Django 2.2.1 on 2019-05-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_auto_20190513_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='LinkModel',
            name='is_clicked_event_from_ground_data',
            field=models.BooleanField(blank=True, default=False)
        ),
        migrations.AddField(
            model_name='LinkModel',
            name='is_clicked_event_from_ground_data_time',
            field=('time_to_view', models.TimeField(blank=True))
        ),
    ]