# Generated by Django 2.2 on 2019-05-16 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20190515_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnew',
            name='question_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.QuestionPage'),
        ),
    ]
