# Generated by Django 2.2.1 on 2019-05-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20190515_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpage',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
