# Generated by Django 2.2.1 on 2019-05-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_questionpage_is_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicenew',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
