# Generated by Django 2.2.1 on 2019-05-25 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20190524_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionNewNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('question_page', models.ManyToManyField(to='survey.QuestionPage')),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.QuestionType')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
