# Generated by Django 2.2.1 on 2019-05-25 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_questionnewnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicenew',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.QuestionNewNew'),
        ),
    ]
