# Generated by Django 2.2.1 on 2019-05-25 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20190524_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicenew',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.QuestionNew'),
        ),
        migrations.DeleteModel(
            name='QuestionNewNew',
        ),
    ]
