# Generated by Django 2.2.1 on 2019-05-25 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20190524_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnew',
            name='question_page',
        ),
    ]
