# Generated by Django 2.2.1 on 2019-05-25 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_remove_questionnew_question_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnew',
            name='question_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.QuestionPage'),
        ),
    ]
